### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by arunasradv** [DiplomacyTeam/Bannerlord.Diplomacy#221]
in WarExhaustionBehavior
now:
 _warExhaustionManager.AddHeroPerishedWarExhaustion(kingdoms, victim, killer.PartyBelongedTo.Name ?? effector!.Name, detail);
fix: 
 _warExhaustionManager.AddHeroPerishedWarExhaustion(kingdoms, victim, killer.PartyBelongedTo?.Name ?? effector!.Name, detail);

**Comment by MKLVN** [comment]
+1 !! Had the same issue, easy fix- would be awesome. Happy to post PR if it'd help

**Comment by bennyz** [comment]
If you have the diff needed to fix, there is no reason not to post a PR

**Comment by arunasradv** [comment]
Hello, will be this fix merged some day? It would be very cool.

**Comment by bennyz** [comment]
> Hello, will be this fix merged some day? It would be very cool.

merged, I'll make a release in the weekend
