### ISSUE TITLE
Crash on new/load game with null pointer on conversation_lord_request_mission_ask_on_condition

### ISSUE THREAD

**Issue by silvanojorge** [DiplomacyTeam/Bannerlord.Diplomacy#235]
Hello!

Today the core game and other official ones had updated.
Bannerlord crashed wtih no other mods than Diplomacy and its dependencies on load or creation game.

[crashreport-190923-null-conversation_lord_request_mission_ask_on_condition.zip](https://github.com/DiplomacyTeam/Bannerlord.Diplomacy/files/12664939/crashreport-190923-null-conversation_lord_request_mission_ask_on_condition.zip)

Thanks

**Comment by punkproger** [comment]
[Uploading crashreport.zip…]()
same

**Comment by silvanojorge** [comment]
It works now, maybe updating harmony.
